"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from qa_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from qa_client.exceptions import ApiAttributeError


def lazy_import():
    from qa_client.model.candidate import Candidate
    from qa_client.model.connection import Connection
    from qa_client.model.modifier_pattern import ModifierPattern
    globals()['Candidate'] = Candidate
    globals()['Connection'] = Connection
    globals()['ModifierPattern'] = ModifierPattern


class MyAnnotation(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'candidates': ([Candidate],),  # noqa: E501
            'connection': (Connection,),  # noqa: E501
            'context': ([int],),  # noqa: E501
            'end': ([int],),  # noqa: E501
            'end_span_in_caracters': ([int],),  # noqa: E501
            'json_answer': (str,),  # noqa: E501
            'knowledge_base_uris': ([str],),  # noqa: E501
            'knowledgebases': ([str],),  # noqa: E501
            'languages': ([str],),  # noqa: E501
            'lexicalization': ([str],),  # noqa: E501
            'modifiers': ([[ModifierPattern]],),  # noqa: E501
            'num_expr': ([str],),  # noqa: E501
            'question': (str,),  # noqa: E501
            'relevances': ([int],),  # noqa: E501
            'respond': (bool,),  # noqa: E501
            'start': ([int],),  # noqa: E501
            'start_span_in_characters': ([int],),  # noqa: E501
            'stop_words': ({str: (str,)},),  # noqa: E501
            'text': ([str],),  # noqa: E501
            'timeml_output': (str,),  # noqa: E501
            'tokens': ([str],),  # noqa: E501
            'uris': ([str],),  # noqa: E501
            'uris_types': ([str],),  # noqa: E501
            'users': ([str],),  # noqa: E501
            'users_uris': ([str],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'candidates': 'candidates',  # noqa: E501
        'connection': 'connection',  # noqa: E501
        'context': 'context',  # noqa: E501
        'end': 'end',  # noqa: E501
        'end_span_in_caracters': 'endSpanInCaracters',  # noqa: E501
        'json_answer': 'jsonAnswer',  # noqa: E501
        'knowledge_base_uris': 'knowledgeBaseUris',  # noqa: E501
        'knowledgebases': 'knowledgebases',  # noqa: E501
        'languages': 'languages',  # noqa: E501
        'lexicalization': 'lexicalization',  # noqa: E501
        'modifiers': 'modifiers',  # noqa: E501
        'num_expr': 'numExpr',  # noqa: E501
        'question': 'question',  # noqa: E501
        'relevances': 'relevances',  # noqa: E501
        'respond': 'respond',  # noqa: E501
        'start': 'start',  # noqa: E501
        'start_span_in_characters': 'startSpanInCharacters',  # noqa: E501
        'stop_words': 'stopWords',  # noqa: E501
        'text': 'text',  # noqa: E501
        'timeml_output': 'timemlOutput',  # noqa: E501
        'tokens': 'tokens',  # noqa: E501
        'uris': 'uris',  # noqa: E501
        'uris_types': 'urisTypes',  # noqa: E501
        'users': 'users',  # noqa: E501
        'users_uris': 'usersUris',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """MyAnnotation - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            candidates ([Candidate]): [optional]  # noqa: E501
            connection (Connection): [optional]  # noqa: E501
            context ([int]): [optional]  # noqa: E501
            end ([int]): [optional]  # noqa: E501
            end_span_in_caracters ([int]): [optional]  # noqa: E501
            json_answer (str): [optional]  # noqa: E501
            knowledge_base_uris ([str]): [optional]  # noqa: E501
            knowledgebases ([str]): [optional]  # noqa: E501
            languages ([str]): [optional]  # noqa: E501
            lexicalization ([str]): [optional]  # noqa: E501
            modifiers ([[ModifierPattern]]): [optional]  # noqa: E501
            num_expr ([str]): [optional]  # noqa: E501
            question (str): [optional]  # noqa: E501
            relevances ([int]): [optional]  # noqa: E501
            respond (bool): [optional]  # noqa: E501
            start ([int]): [optional]  # noqa: E501
            start_span_in_characters ([int]): [optional]  # noqa: E501
            stop_words ({str: (str,)}): [optional]  # noqa: E501
            text ([str]): [optional]  # noqa: E501
            timeml_output (str): [optional]  # noqa: E501
            tokens ([str]): [optional]  # noqa: E501
            uris ([str]): [optional]  # noqa: E501
            uris_types ([str]): [optional]  # noqa: E501
            users ([str]): [optional]  # noqa: E501
            users_uris ([str]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """MyAnnotation - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            candidates ([Candidate]): [optional]  # noqa: E501
            connection (Connection): [optional]  # noqa: E501
            context ([int]): [optional]  # noqa: E501
            end ([int]): [optional]  # noqa: E501
            end_span_in_caracters ([int]): [optional]  # noqa: E501
            json_answer (str): [optional]  # noqa: E501
            knowledge_base_uris ([str]): [optional]  # noqa: E501
            knowledgebases ([str]): [optional]  # noqa: E501
            languages ([str]): [optional]  # noqa: E501
            lexicalization ([str]): [optional]  # noqa: E501
            modifiers ([[ModifierPattern]]): [optional]  # noqa: E501
            num_expr ([str]): [optional]  # noqa: E501
            question (str): [optional]  # noqa: E501
            relevances ([int]): [optional]  # noqa: E501
            respond (bool): [optional]  # noqa: E501
            start ([int]): [optional]  # noqa: E501
            start_span_in_characters ([int]): [optional]  # noqa: E501
            stop_words ({str: (str,)}): [optional]  # noqa: E501
            text ([str]): [optional]  # noqa: E501
            timeml_output (str): [optional]  # noqa: E501
            tokens ([str]): [optional]  # noqa: E501
            uris ([str]): [optional]  # noqa: E501
            uris_types ([str]): [optional]  # noqa: E501
            users ([str]): [optional]  # noqa: E501
            users_uris ([str]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
