"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.time_controller_api import TimeControllerApi  # noqa: E501


class TestTimeControllerApi(unittest.TestCase):
    """TimeControllerApi unit test stubs"""

    def setUp(self):
        self.api = TimeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_time_using_get(self):
        """Test case for time_using_get

        Identifies dates in a sentence  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
