"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.document_model import DocumentModel
globals()['DocumentModel'] = DocumentModel
from qa_client.model.index_model import IndexModel


class TestIndexModel(unittest.TestCase):
    """IndexModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexModel(self):
        """Test IndexModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
