"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.qa_controller_combined_api import QaControllerCombinedApi  # noqa: E501


class TestQaControllerCombinedApi(unittest.TestCase):
    """QaControllerCombinedApi unit test stubs"""

    def setUp(self):
        self.api = QaControllerCombinedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_qa_combined_using_post(self):
        """Test case for qa_combined_using_post

        qaCombined  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
