"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.rdf_facet_browser_controller_api import RdfFacetBrowserControllerApi  # noqa: E501


class TestRdfFacetBrowserControllerApi(unittest.TestCase):
    """RdfFacetBrowserControllerApi unit test stubs"""

    def setUp(self):
        self.api = RdfFacetBrowserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rdf_using_get(self):
        """Test case for rdf_using_get

        Gets back the RDF content to render  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
