"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.modifier_pattern import ModifierPattern
from qa_client.model.node import Node
from qa_client.model.triple import Triple
globals()['ModifierPattern'] = ModifierPattern
globals()['Node'] = Node
globals()['Triple'] = Triple
from qa_client.model.candidate import Candidate


class TestCandidate(unittest.TestCase):
    """Candidate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCandidate(self):
        """Test Candidate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Candidate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
