"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.free_text_general_controller_api import FreeTextGeneralControllerApi  # noqa: E501


class TestFreeTextGeneralControllerApi(unittest.TestCase):
    """FreeTextGeneralControllerApi unit test stubs"""

    def setUp(self):
        self.api = FreeTextGeneralControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_free_text_check_elastic_search_using_get(self):
        """Test case for free_text_check_elastic_search_using_get

        freeTextCheckElasticSearch  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
