"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.suggestor_controller_api import SuggestorControllerApi  # noqa: E501


class TestSuggestorControllerApi(unittest.TestCase):
    """SuggestorControllerApi unit test stubs"""

    def setUp(self):
        self.api = SuggestorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_example_questions_using_get(self):
        """Test case for example_questions_using_get

        Returns example questions based on the questions that are approved in the training dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
