"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.store_website_response import StoreWebsiteResponse


class TestStoreWebsiteResponse(unittest.TestCase):
    """StoreWebsiteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreWebsiteResponse(self):
        """Test StoreWebsiteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoreWebsiteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
