"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.question_context import QuestionContext
globals()['QuestionContext'] = QuestionContext
from qa_client.model.chat_request_train import ChatRequestTrain


class TestChatRequestTrain(unittest.TestCase):
    """ChatRequestTrain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatRequestTrain(self):
        """Test ChatRequestTrain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChatRequestTrain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
