"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.free_text_source_controller_api import FreeTextSourceControllerApi  # noqa: E501


class TestFreeTextSourceControllerApi(unittest.TestCase):
    """FreeTextSourceControllerApi unit test stubs"""

    def setUp(self):
        self.api = FreeTextSourceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_extract_snippet_using_post(self):
        """Test case for extract_snippet_using_post

        extract_snippet  # noqa: E501
        """
        pass

    def test_extract_website_using_post(self):
        """Test case for extract_website_using_post

        extract_website  # noqa: E501
        """
        pass

    def test_store_website_using_post(self):
        """Test case for store_website_using_post

        store_website  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
