"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.candidate import Candidate
from qa_client.model.connection import Connection
from qa_client.model.modifier_pattern import ModifierPattern
globals()['Candidate'] = Candidate
globals()['Connection'] = Connection
globals()['ModifierPattern'] = ModifierPattern
from qa_client.model.my_annotation import MyAnnotation


class TestMyAnnotation(unittest.TestCase):
    """MyAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMyAnnotation(self):
        """Test MyAnnotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MyAnnotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
