"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.labeled_node import LabeledNode
globals()['LabeledNode'] = LabeledNode
from qa_client.model.fact import Fact


class TestFact(unittest.TestCase):
    """Fact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFact(self):
        """Test Fact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
