"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.download_controller_api import DownloadControllerApi  # noqa: E501


class TestDownloadControllerApi(unittest.TestCase):
    """DownloadControllerApi unit test stubs"""

    def setUp(self):
        self.api = DownloadControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_steaming_file_using_get(self):
        """Test case for get_steaming_file_using_get

        getSteamingFile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
