"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.user_controller_api import UserControllerApi  # noqa: E501


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self):
        self.api = UserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_all_using_get(self):
        """Test case for admin_all_using_get

        Get a list of all users  # noqa: E501
        """
        pass

    def test_admin_remove_using_post(self):
        """Test case for admin_remove_using_post

        Remove a user  # noqa: E501
        """
        pass

    def test_admin_signup_using_post(self):
        """Test case for admin_signup_using_post

        Create a new user  # noqa: E501
        """
        pass

    def test_change_password_admin_using_post(self):
        """Test case for change_password_admin_using_post

        Change the password for a user  # noqa: E501
        """
        pass

    def test_change_password_login_using_post(self):
        """Test case for change_password_login_using_post

        Change the password for a user that is able to login  # noqa: E501
        """
        pass

    def test_change_password_using_post(self):
        """Test case for change_password_using_post

        Change the password for a user using the key send by email  # noqa: E501
        """
        pass

    def test_check_email_availability_using_get(self):
        """Test case for check_email_availability_using_get

        Check if e-mail is available  # noqa: E501
        """
        pass

    def test_check_username_availability_using_get(self):
        """Test case for check_username_availability_using_get

        Check if username is available  # noqa: E501
        """
        pass

    def test_confirm_registration_using_get(self):
        """Test case for confirm_registration_using_get

        Confirm key of a user send by e-mail on registration  # noqa: E501
        """
        pass

    def test_me_using_get(self):
        """Test case for me_using_get

        Information of a user  # noqa: E501
        """
        pass

    def test_remove_using_get(self):
        """Test case for remove_using_get

        Remove a user  # noqa: E501
        """
        pass

    def test_reset_password_using_post(self):
        """Test case for reset_password_using_post

        Ask to reset a password for a user  # noqa: E501
        """
        pass

    def test_set_cookie_using_get(self):
        """Test case for set_cookie_using_get

        Set a cookie for the user  # noqa: E501
        """
        pass

    def test_signin_using_post(self):
        """Test case for signin_using_post

        User login  # noqa: E501
        """
        pass

    def test_signup_using_post(self):
        """Test case for signup_using_post

        Create a new user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
