"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.dataset import Dataset
globals()['Dataset'] = Dataset
from qa_client.model.eu_qanswer_core2_server_controller_payload_combined_question import EuQanswerCore2ServerControllerPayloadCombinedQuestion


class TestEuQanswerCore2ServerControllerPayloadCombinedQuestion(unittest.TestCase):
    """EuQanswerCore2ServerControllerPayloadCombinedQuestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEuQanswerCore2ServerControllerPayloadCombinedQuestion(self):
        """Test EuQanswerCore2ServerControllerPayloadCombinedQuestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EuQanswerCore2ServerControllerPayloadCombinedQuestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
