"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.free_text_feedback_controller_api import FreeTextFeedbackControllerApi  # noqa: E501


class TestFreeTextFeedbackControllerApi(unittest.TestCase):
    """FreeTextFeedbackControllerApi unit test stubs"""

    def setUp(self):
        self.api = FreeTextFeedbackControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_free_text_feedback_creation_using_post(self):
        """Test case for free_text_feedback_creation_using_post

        freeTextFeedbackCreation  # noqa: E501
        """
        pass

    def test_free_text_feedback_deletion_using_delete(self):
        """Test case for free_text_feedback_deletion_using_delete

        freeTextFeedbackDeletion  # noqa: E501
        """
        pass

    def test_free_text_feedback_list_using_get(self):
        """Test case for free_text_feedback_list_using_get

        freeTextFeedbackList  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
