"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.document_meta import DocumentMeta
from qa_client.model.offsets_context import OffsetsContext
from qa_client.model.offsets_document import OffsetsDocument
globals()['DocumentMeta'] = DocumentMeta
globals()['OffsetsContext'] = OffsetsContext
globals()['OffsetsDocument'] = OffsetsDocument
from qa_client.model.answer_model import AnswerModel


class TestAnswerModel(unittest.TestCase):
    """AnswerModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnswerModel(self):
        """Test AnswerModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnswerModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
