"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.free_text_job_controller_api import FreeTextJobControllerApi  # noqa: E501


class TestFreeTextJobControllerApi(unittest.TestCase):
    """FreeTextJobControllerApi unit test stubs"""

    def setUp(self):
        self.api = FreeTextJobControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_free_text_job_list_using_get(self):
        """Test case for free_text_job_list_using_get

        freeTextJobList  # noqa: E501
        """
        pass

    def test_free_text_job_terminated_using_get(self):
        """Test case for free_text_job_terminated_using_get

        freeTextJobTerminated  # noqa: E501
        """
        pass

    def test_free_text_job_update_using_put(self):
        """Test case for free_text_job_update_using_put

        freeTextJobUpdate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
