"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.sparql_endpoint_controller_api import SparqlEndpointControllerApi  # noqa: E501


class TestSparqlEndpointControllerApi(unittest.TestCase):
    """SparqlEndpointControllerApi unit test stubs"""

    def setUp(self):
        self.api = SparqlEndpointControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sparql_endpoint_using_get(self):
        """Test case for sparql_endpoint_using_get

        SPARQL endpoint over a dataset  # noqa: E501
        """
        pass

    def test_sparql_endpoint_using_post(self):
        """Test case for sparql_endpoint_using_post

        SPARQL endpoint over a dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
