"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.extract_content_meta import ExtractContentMeta
globals()['ExtractContentMeta'] = ExtractContentMeta
from qa_client.model.extract_content_response import ExtractContentResponse


class TestExtractContentResponse(unittest.TestCase):
    """ExtractContentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtractContentResponse(self):
        """Test ExtractContentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExtractContentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
