"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.qa_controller_kb_api import QaControllerKbApi  # noqa: E501


class TestQaControllerKbApi(unittest.TestCase):
    """QaControllerKbApi unit test stubs"""

    def setUp(self):
        self.api = QaControllerKbApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gerbil_using_post(self):
        """Test case for gerbil_using_post

        Takes a question and returns the answer in the format specified by the GERBIL API  # noqa: E501
        """
        pass

    def test_qa_full_interpretation_using_get(self):
        """Test case for qa_full_interpretation_using_get

        Takes a question and returns the SPARQL query, the answer, contextual information about the answer and the interpretation.  # noqa: E501
        """
        pass

    def test_qa_full_using_get(self):
        """Test case for qa_full_using_get

        Takes a question and returns the SPARQL query, the answer and contextual information about the answer.  # noqa: E501
        """
        pass

    def test_qa_sparql_using_get(self):
        """Test case for qa_sparql_using_get

        Takes a question and returns the corresponding SPARQL query.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
