"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.answer_controller_api import AnswerControllerApi  # noqa: E501


class TestAnswerControllerApi(unittest.TestCase):
    """AnswerControllerApi unit test stubs"""

    def setUp(self):
        self.api = AnswerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_answer_context_using_get(self):
        """Test case for answer_context_using_get

        Given a SPARQL query returns all information about the answer entities like label, description, images ...   # noqa: E501
        """
        pass

    def test_table_context_using_get(self):
        """Test case for table_context_using_get

        Given a SPARQL query returns the information about the answer entities in the form of a table.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
