"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.auto_complete_controller_api import AutoCompleteControllerApi  # noqa: E501


class TestAutoCompleteControllerApi(unittest.TestCase):
    """AutoCompleteControllerApi unit test stubs"""

    def setUp(self):
        self.api = AutoCompleteControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_autocomplete_using_post(self):
        """Test case for autocomplete_using_post

        Given a prefix   # noqa: E501
        """
        pass

    def test_index_autocomplete_data_using_get(self):
        """Test case for index_autocomplete_data_using_get

        Creates the autocompletion index given the data  # noqa: E501
        """
        pass

    def test_index_autocomplete_questions_using_get(self):
        """Test case for index_autocomplete_questions_using_get

        Creates the autocompletion index given the questions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
