"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.summa_server_controller_api import SummaServerControllerApi  # noqa: E501


class TestSummaServerControllerApi(unittest.TestCase):
    """SummaServerControllerApi unit test stubs"""

    def setUp(self):
        self.api = SummaServerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_summa_using_get(self):
        """Test case for summa_using_get

        Generates summaries, i.e. most relevant top-k properties, for an item in a dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
