"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.link_controller_api import LinkControllerApi  # noqa: E501


class TestLinkControllerApi(unittest.TestCase):
    """LinkControllerApi unit test stubs"""

    def setUp(self):
        self.api = LinkControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_evaluate_using_get1(self):
        """Test case for evaluate_using_get1

        evaluate  # noqa: E501
        """
        pass

    def test_link2_using_post(self):
        """Test case for link2_using_post

        link2  # noqa: E501
        """
        pass

    def test_link3_train_using_post(self):
        """Test case for link3_train_using_post

        link3Train  # noqa: E501
        """
        pass

    def test_link3_upload_using_post(self):
        """Test case for link3_upload_using_post

        link3Upload  # noqa: E501
        """
        pass

    def test_link3_using_post(self):
        """Test case for link3_using_post

        link3  # noqa: E501
        """
        pass

    def test_link3generate_features_using_post(self):
        """Test case for link3generate_features_using_post

        link3generateFeatures  # noqa: E501
        """
        pass

    def test_link_aggregate_using_get(self):
        """Test case for link_aggregate_using_get

        linkAggregate  # noqa: E501
        """
        pass

    def test_link_aggregate_using_post(self):
        """Test case for link_aggregate_using_post

        linkAggregate  # noqa: E501
        """
        pass

    def test_link_analyze_using_post(self):
        """Test case for link_analyze_using_post

        linkAnalyze  # noqa: E501
        """
        pass

    def test_link_delete_using_post(self):
        """Test case for link_delete_using_post

        Deletes a dataset for linking. The request contains the dataset name  # noqa: E501
        """
        pass

    def test_link_evaluate_using_get(self):
        """Test case for link_evaluate_using_get

        linkEvaluate  # noqa: E501
        """
        pass

    def test_link_evaluate_using_post(self):
        """Test case for link_evaluate_using_post

        linkEvaluate  # noqa: E501
        """
        pass

    def test_link_kohesio_using_get(self):
        """Test case for link_kohesio_using_get

        linkKohesio  # noqa: E501
        """
        pass

    def test_link_list_using_get(self):
        """Test case for link_list_using_get

        Loads a new dataset to link. The request contains the dataset name, the Knowledgegraph to link to, the languages and the text,uri pairs  # noqa: E501
        """
        pass

    def test_link_load_using_post(self):
        """Test case for link_load_using_post

        Loads a new dataset to link. The request contains the dataset name, the Knowledgegraph to link to, the languages and the text,uri pairs  # noqa: E501
        """
        pass

    def test_link_result_using_get(self):
        """Test case for link_result_using_get

        linkResult  # noqa: E501
        """
        pass

    def test_link_train_using_post(self):
        """Test case for link_train_using_post

        linkTrain  # noqa: E501
        """
        pass

    def test_link_using_get(self):
        """Test case for link_using_get

        link  # noqa: E501
        """
        pass

    def test_link_using_post(self):
        """Test case for link_using_post

        link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
