"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.index_model import IndexModel
globals()['IndexModel'] = IndexModel
from qa_client.model.read_documents_response import ReadDocumentsResponse


class TestReadDocumentsResponse(unittest.TestCase):
    """ReadDocumentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadDocumentsResponse(self):
        """Test ReadDocumentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReadDocumentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
