"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.qa_controller_free_text_api import QaControllerFreeTextApi  # noqa: E501


class TestQaControllerFreeTextApi(unittest.TestCase):
    """QaControllerFreeTextApi unit test stubs"""

    def setUp(self):
        self.api = QaControllerFreeTextApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_free_text_qa_predict_on_text_using_get(self):
        """Test case for free_text_qa_predict_on_text_using_get

        freeTextQAPredictOnText  # noqa: E501
        """
        pass

    def test_free_text_qa_predict_on_website_using_get(self):
        """Test case for free_text_qa_predict_on_website_using_get

        freeTextQAPredictOnWebsite  # noqa: E501
        """
        pass

    def test_free_text_qa_predict_using_get(self):
        """Test case for free_text_qa_predict_using_get

        freeTextQAPredict  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
