"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.qa_context import QaContext
from qa_client.model.qa_table import QaTable
globals()['QaContext'] = QaContext
globals()['QaTable'] = QaTable
from qa_client.model.qa_contexts import QaContexts


class TestQaContexts(unittest.TestCase):
    """QaContexts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQaContexts(self):
        """Test QaContexts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QaContexts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
