"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.feedback_controller_api import FeedbackControllerApi  # noqa: E501


class TestFeedbackControllerApi(unittest.TestCase):
    """FeedbackControllerApi unit test stubs"""

    def setUp(self):
        self.api = FeedbackControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_train_using_get(self):
        """Test case for admin_train_using_get

        Retrain all datasets models based on the uploaded question-answer pairs  # noqa: E501
        """
        pass

    def test_create_features_api_using_post(self):
        """Test case for create_features_api_using_post

        Give new feedback for a question answer pair  # noqa: E501
        """
        pass

    def test_dump_admin_using_get(self):
        """Test case for dump_admin_using_get

        Download all question-answer pairs  # noqa: E501
        """
        pass

    def test_dump_features_using_get(self):
        """Test case for dump_features_using_get

        Train a model based on the uploaded question-answer pairs  # noqa: E501
        """
        pass

    def test_dump_qald_using_get(self):
        """Test case for dump_qald_using_get

        Download all question-answer pairs in QALD format  # noqa: E501
        """
        pass

    def test_dump_suggestor_using_get(self):
        """Test case for dump_suggestor_using_get

        dumpSuggestor  # noqa: E501
        """
        pass

    def test_dump_using_get(self):
        """Test case for dump_using_get

        Download all question-answer pairs  # noqa: E501
        """
        pass

    def test_evaluate_using_get(self):
        """Test case for evaluate_using_get

        Evaluate the current model on the uploaded question-answer pairs  # noqa: E501
        """
        pass

    def test_feedback_upload_using_post(self):
        """Test case for feedback_upload_using_post

        Upload question-answer pairs  # noqa: E501
        """
        pass

    def test_remove_all_admin_using_post(self):
        """Test case for remove_all_admin_using_post

        Remove all the feedback given  # noqa: E501
        """
        pass

    def test_remove_all_using_post(self):
        """Test case for remove_all_using_post

        Remove all given question-answer pairs  # noqa: E501
        """
        pass

    def test_remove_using_post2(self):
        """Test case for remove_using_post2

        Remove one question-answer pair  # noqa: E501
        """
        pass

    def test_train_using_get(self):
        """Test case for train_using_get

        Train a model based on the uploaded question-answer pairs  # noqa: E501
        """
        pass

    def test_upload_admin_using_post(self):
        """Test case for upload_admin_using_post

        Upload question-answer pairs  # noqa: E501
        """
        pass

    def test_upload_qald_using_post(self):
        """Test case for upload_qald_using_post

        Upload question-answer pairs in QALD format  # noqa: E501
        """
        pass

    def test_upload_specific_using_post(self):
        """Test case for upload_specific_using_post

        Upload question-answer pairs for specific dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
