"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.custom_error_controller_api import CustomErrorControllerApi  # noqa: E501


class TestCustomErrorControllerApi(unittest.TestCase):
    """CustomErrorControllerApi unit test stubs"""

    def setUp(self):
        self.api = CustomErrorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_error_using_delete(self):
        """Test case for error_using_delete

        error  # noqa: E501
        """
        pass

    def test_error_using_get(self):
        """Test case for error_using_get

        error  # noqa: E501
        """
        pass

    def test_error_using_head(self):
        """Test case for error_using_head

        error  # noqa: E501
        """
        pass

    def test_error_using_options(self):
        """Test case for error_using_options

        error  # noqa: E501
        """
        pass

    def test_error_using_patch(self):
        """Test case for error_using_patch

        error  # noqa: E501
        """
        pass

    def test_error_using_post(self):
        """Test case for error_using_post

        error  # noqa: E501
        """
        pass

    def test_error_using_put(self):
        """Test case for error_using_put

        error  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
