"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.sparql_controller_api import SparqlControllerApi  # noqa: E501


class TestSparqlControllerApi(unittest.TestCase):
    """SparqlControllerApi unit test stubs"""

    def setUp(self):
        self.api = SparqlControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sparql_compare_answers_using_get(self):
        """Test case for sparql_compare_answers_using_get

        Compares two sparql query based on the answer set  # noqa: E501
        """
        pass

    def test_sparql_compare_sparql_using_get(self):
        """Test case for sparql_compare_sparql_using_get

        Compares two sparql query based on the structure  # noqa: E501
        """
        pass

    def test_sparql_to_user_using_get(self):
        """Test case for sparql_to_user_using_get

        Convertes a SPARQL query in a human readable interpretation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
