"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.free_text_static_controller_api import FreeTextStaticControllerApi  # noqa: E501


class TestFreeTextStaticControllerApi(unittest.TestCase):
    """FreeTextStaticControllerApi unit test stubs"""

    def setUp(self):
        self.api = FreeTextStaticControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resource_pdf_using_get(self):
        """Test case for resource_pdf_using_get

        resource_pdf  # noqa: E501
        """
        pass

    def test_resource_using_get(self):
        """Test case for resource_using_get

        resource  # noqa: E501
        """
        pass

    def test_resource_using_get1(self):
        """Test case for resource_using_get1

        resource  # noqa: E501
        """
        pass

    def test_serve_iframe_using_get(self):
        """Test case for serve_iframe_using_get

        serveIframe  # noqa: E501
        """
        pass

    def test_serve_using_get(self):
        """Test case for serve_using_get

        serve  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
