"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qa_client
from qa_client.model.fact import Fact
from qa_client.model.labeled_node import LabeledNode
globals()['Fact'] = Fact
globals()['LabeledNode'] = LabeledNode
from qa_client.model.summa_server import SummaServer


class TestSummaServer(unittest.TestCase):
    """SummaServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummaServer(self):
        """Test SummaServer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SummaServer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
