"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import qa_client
from qa_client.api.question_log_controller_api import QuestionLogControllerApi  # noqa: E501


class TestQuestionLogControllerApi(unittest.TestCase):
    """QuestionLogControllerApi unit test stubs"""

    def setUp(self):
        self.api = QuestionLogControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_evaluate_using_get2(self):
        """Test case for evaluate_using_get2

        Evaluate the current model on the uploaded question-answer pairs  # noqa: E501
        """
        pass

    def test_log_question_using_post(self):
        """Test case for log_question_using_post

        Give new question  # noqa: E501
        """
        pass

    def test_question_log_remove_all_using_post(self):
        """Test case for question_log_remove_all_using_post

        Remove all the feedback given  # noqa: E501
        """
        pass

    def test_question_log_remove_using_post(self):
        """Test case for question_log_remove_using_post

        Remove one question-answer pair  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
