# flake8: noqa

"""
    QAnswer: Api Documentation

    APIs provided by QAnswer  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@qanswer.eu
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from qa_client.api_client import ApiClient

# import Configuration
from qa_client.configuration import Configuration

# import exceptions
from qa_client.exceptions import OpenApiException
from qa_client.exceptions import ApiAttributeError
from qa_client.exceptions import ApiTypeError
from qa_client.exceptions import ApiValueError
from qa_client.exceptions import ApiKeyError
from qa_client.exceptions import ApiException
